#!/usr/bin/env bash
# fetches domain and subdomain
if [ $# -eq 1 ]; then
	domains="www.$1 441483-lb-01.$1 441483-web-01.$1 441483-web-02.$1"
else
	domains="$2.$1"
fi
dig $domains | awk '/ANSWER SECTION:/ { getline; split($1, a, "."); print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
