#!/usr/bin/env bash
# configuration script for a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
