#!/usr/bin/env bash
# nginx config by automation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "15i \\\tadd_header X-Served-By 441483-web-01;" /etc/nginx/nginx.conf
sudo service nginx restart
