#!/usr/bin/env bash
# Configuring HAProxy load balancer

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 441483-web-01 100.27.14.242
        server 441483-web-02 3.84.255.61" >> /etc/haproxy/haproxy.cfg

service haproxy restart
