#!/usr/bin/env bash
#  a Bash script that displays numbers from 1 to 100.
#    Displays FizzBuzz when the number is a multiple of 3 and 5
#    Displays Fizz when the number is multiple of 3
#    Displays Buzz when the number is a multiple of 5
#    Otherwise, displays the number
#    In a list format

i=0
while [ $((i++)) -lt 100 ]; do
	if [ $((i % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo $i
	fi
done
