#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
#Your script should only display:
#    username
#    user id
#    Home directory path for the user
exec 3< /etc/passwd
while read -ru 3; do
	echo "$REPLY" | cut -d':' -f1,3,6
done
