#!/usr/bin/env bash
# a Bash script that groups visitors by IP and HTTP status code, and displays this data.
awk 'BEGIN { FS = " " } ; { print $1, $9 }' apache-access.log | sort -b | uniq -c | sort -b
